export const TOGGLE_CHAT = 'TOGGLE_CHAT';
export const TOGGLE_INPUT_DISABLED = 'TOGGLE_INPUT_DISABLED';
export const CHANGE_INPUT_FIELD_HINT = 'CHANGE_INOUT_FIELD_HINT';
export const ADD_NEW_USER_MESSAGE = 'ADD_NEW_USER_MESSAGE';
export const ADD_NEW_RESPONSE_MESSAGE = 'ADD_NEW_RESPONSE_MESSAGE';
export const ADD_NEW_LINK_SNIPPET = 'ADD_NEW_LINK_SNIPPET';
export const ADD_COMPONENT_MESSAGE = 'ADD_COMPONENT_MESSAGE';
export const ADD_QUICK_REPLY = 'ADD_QUICK_REPLY';
export const SET_QUICK_REPLY = 'SET_QUICK_REPLY';
export const INSERT_NEW_USER_MESSAGE = 'INSERT_NEW_USER_MESSAGE';
export const DROP_MESSAGES = 'DROP_MESSAGES';

